ALTER TABLE notes
  ADD COLUMN cv_dep_x NUMERIC(78, 0) NOT NULL DEFAULT 0,
  ADD COLUMN cv_dep_y NUMERIC(78, 0) NOT NULL DEFAULT 0;

ALTER TABLE notes
  ALTER COLUMN cv_dep_x DROP DEFAULT,
  ALTER COLUMN cv_dep_y DROP DEFAULT;
