//! Cross-implementation Poseidon parity.
//!
//! The vectors are generated by the SDK (`sdk/scripts/gen-poseidon-vectors.ts`)
//! from `poseidon-lite` and verified here against this crate's permutation. The
//! check is absolute rather than relative: both sides are pinned to circomlib's
//! published digests via `anchors`, so a constants change under a dependency bump
//! cannot move both implementations together unnoticed. See
//! `poseidon::tests::golden_digests_are_stable`.
//!
//! `sdk/wasm/poseidon` vendors this crate's permutation, so this file also covers
//! the vendored copy.

use ark_ed_on_bn254::Fq;
use ark_ff::{BigInteger, PrimeField};
use fmd_crypto::poseidon::hash;
use serde::Deserialize;
use std::str::FromStr;
use std::sync::LazyLock;

#[derive(Debug, Deserialize)]
struct VectorFile {
    anchors: Vec<Vector>,
    vectors: Vec<Vector>,
}

#[derive(Debug, Deserialize)]
struct Vector {
    label: String,
    /// Decimal field elements.
    inputs: Vec<String>,
    /// Decimal digest.
    digest: String,
}

/// Read and parsed once, since both tests below use the whole file.
static FILE: LazyLock<VectorFile> = LazyLock::new(|| {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/vectors/poseidon.json"
    ))
    .expect("read tests/vectors/poseidon.json");
    serde_json::from_str(&text).expect("parse poseidon.json")
});

fn dec(s: &str) -> Fq {
    Fq::from_str(s).expect("decimal field element")
}

/// Decimal, to compare against the JSON without depending on byte order.
fn to_dec(f: &Fq) -> String {
    num_bigint::BigUint::from_bytes_be(&f.into_bigint().to_bytes_be()).to_str_radix(10)
}

fn check(v: &Vector) {
    let inputs: Vec<Fq> = v.inputs.iter().map(|s| dec(s)).collect();
    let got = hash(&inputs).unwrap_or_else(|e| panic!("{}: {e}", v.label));
    assert_eq!(to_dec(&got), v.digest, "{}", v.label);
}

/// The circomlib-published digests. A failure here means the constants moved.
#[test]
fn anchors_match_circomlib() {
    assert!(!FILE.anchors.is_empty(), "anchors must not be empty");
    for v in &FILE.anchors {
        check(v);
    }
}

#[test]
fn vectors_match_the_sdk() {
    assert!(!FILE.vectors.is_empty(), "vectors must not be empty");
    for v in &FILE.vectors {
        check(v);
    }
}
