[package]
name = "ingester"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ingester"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared", features = ["metrics-exporter"] }
database = { path = "../database" }
chain-types = { path = "../chain-types" }
tokio = { workspace = true }
futures = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
bb8 = { workspace = true }
alloy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
dotenvy = { workspace = true }
hex = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
rand = { workspace = true }
metrics = { workspace = true }

[dev-dependencies]
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }

[build-dependencies]
vergen-gix = "9"
