-- Client-facing capability token for a subscription.
--
-- `subscriptions.id` is a dense BIGSERIAL, so keying `/v1/matches` and
-- `DELETE /v1/subscriptions` on it let any caller walk `id = 1..N` and read
-- (or delete) every user's note set. The token replaces the id as the
-- client-facing handle: 32 bytes from the OS CSPRNG, generated by the
-- webserver on insert, returned once at create time and never listed. `id`
-- stays as the internal FK target for `matches`.
--
-- Nullable on purpose. Rows that predate this migration were registered
-- before tokens existed, so nobody holds a token for them; inventing one
-- would either need a weak in-database RNG or a Postgres version floor, and
-- would hand out a credential no client ever received. A NULL token simply
-- never matches a lookup (`token = $1` is never true for NULL), so those
-- rows keep filtering and are unreachable through the token endpoints until
-- their owners re-register. The partial UNIQUE index enforces uniqueness
-- over the real tokens without counting NULLs against each other.

ALTER TABLE subscriptions ADD COLUMN token BYTEA;

CREATE UNIQUE INDEX subscriptions_token_idx
    ON subscriptions (token)
    WHERE token IS NOT NULL;
