[package]
name = "registry-webserver"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "registry-webserver"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared", features = ["webserver", "metrics-exporter"] }
database = { path = "../database" }
asset-registry = { path = "../asset-registry", features = ["http"] }
chain-types = { path = "../chain-types", features = ["rpc"] }
prices = { path = "../prices" }
tokio = { workspace = true }
axum = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
alloy = { workspace = true }
bigdecimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
dotenvy = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }

[dev-dependencies]
test-support = { path = "../test-support" }

[build-dependencies]
vergen-gix = { workspace = true }
