[package]
name = "relayer"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "relayer"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared", features = ["webserver"] }
database = { path = "../database" }
asset-registry = { path = "../asset-registry" }
crypto = { path = "../crypto" }
groth16 = { path = "../groth16" }
tokio = { workspace = true, features = ["fs"] }
futures = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
dotenvy = { workspace = true }
hex = { workspace = true }
async-trait = { workspace = true }
chain-types = { path = "../chain-types", features = ["rpc"] }
alloy = { workspace = true }
bigdecimal = { workspace = true }
bech32 = { workspace = true }
tokio-stream = { version = "0.1", features = ["sync"] }
reqwest = { workspace = true }

parking_lot = "0.12"
rayon = { workspace = true }

[dev-dependencies]
test-support = { path = "../test-support" }

[build-dependencies]
vergen-gix = { workspace = true }

