[package]
name = "metaquoter"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "metaquoter"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared", features = ["webserver"] }
tokio = { workspace = true }
futures = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
dotenvy = { workspace = true }
async-trait = { workspace = true }
chain-types = { path = "../chain-types", features = ["rpc"] }
alloy = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[build-dependencies]
vergen-gix = { workspace = true }
