[package]
name = "test-support"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
database = { path = "../database" }
shared = { path = "../shared" }
alloy = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
tokio = { workspace = true }
